version: '3.8'
services:
  mysql:
    image: mysql:8.0.33
    environment:
      - MYSQL_DATABASE=nottodo
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

